services:
  db:
    image: postgres:16-alpine
    container_name: fitvibe_db
    environment:
      POSTGRES_USER: fitvibe
      POSTGRES_PASSWORD: fitvibe
      POSTGRES_DB: fitvibe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.backend
    container_name: fitvibe_backend
    # The file lives NEXT to this compose file, so no "infra/infra" mistake
    env_file: ./.env.example
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.frontend
    container_name: fitvibe_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"   # local dev browser → nginx:80

  nginx:
    image: nginx:stable-alpine
    container_name: fitvibe_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
