services:
  db:
    image: postgres:16-alpine
    container_name: fitvibe_db
    environment:
      POSTGRES_USER: fitvibe
      POSTGRES_PASSWORD: fitvibe
      POSTGRES_DB: fitvibe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  clamav:
    image: clamav/clamav:latest
    container_name: fitvibe_clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 300s  # ClamAV needs time to download virus definitions
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: fitvibe_vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-only-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
    command: server -dev -dev-root-token-id="dev-only-token"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: ./infra/docker/dev/Dockerfile.backend
      target: runtime
    container_name: fitvibe_backend
    # The file lives NEXT to this compose file, so no "infra/infra" mistake
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://fitvibe:fitvibe@db:5432/fitvibe
    env_file: ./.env.example
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      # live-reload / hot-reload mounting for local dev
      - ../keys:/app/keys:ro
      - ../apps/backend/src:/app/apps/backend/src:ro
      - ../packages:/app/packages:ro

    networks:
      default:
        aliases:
          - fitvibe_backend
  frontend:
    build:
      context: ..
      dockerfile: ./infra/docker/dev/Dockerfile.frontend
    container_name: fitvibe_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80" # local dev browser → nginx:80
    environment:
      VITE_API_URL: http://localhost:4000
  nginx:
    image: nginx:stable-alpine
    container_name: fitvibe_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  clamav_data:
  vault_data:
  vault_logs:
networks:
  default:
    name: fitvibe_net
    driver: bridge
