services:
  db:
    image: postgres:16-alpine
    container_name: fitvibe_db
    environment:
      POSTGRES_USER: fitvibe
      POSTGRES_PASSWORD: fitvibe
      POSTGRES_DB: fitvibe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.backend
      target: runtime
    container_name: fitvibe_backend
    # The file lives NEXT to this compose file, so no "infra/infra" mistake
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://fitvibe:fitvibe@db:5432/fitvibe
    env_file: ./.env.example
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      # live-reload / hot-reload mounting for local dev
      - ../apps/backend/src:/app/apps/backend/src:ro
      - ../packages:/app/packages:ro
  frontend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.frontend
      target: builder
    container_name: fitvibe_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80" # local dev browser → nginx:80
    environment:
      VITE_API_URL: http://localhost:3000
  nginx:
    image: nginx:stable-alpine
    container_name: fitvibe_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
networks:
  default:
    name: fitvibe_net
    driver: bridge
