services:
  db:
    image: postgres:16-alpine
    container_name: fitvibe_db
    environment:
      POSTGRES_USER: fitvibe
      POSTGRES_PASSWORD: fitvibe
      POSTGRES_DB: fitvibe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../../..
      dockerfile: infra/docker/dev/Dockerfile.backend
    container_name: fitvibe_backend
    env_file: ../../.env.example
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ../keys:/app/keys:ro
      - ../../apps/backend/src:/app/apps/backend/src:ro
      - ../../packages:/app/packages:ro
    networks:
      default:
        aliases:
          - fitvibe_backend

  frontend:
    build:
      context: ../../..
      dockerfile: infra/docker/dev/Dockerfile.frontend
    container_name: fitvibe_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

  nginx:
    image: nginx:stable-alpine
    container_name: fitvibe_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
